// AUTO-GENERATED by `bun run cf-typegen`. Do not edit manually.
// Edit wrangler.jsonc instead, then run `bun run --filter @app/api cf-typegen`.
//
// This is a minimal hand-written stub shipped with the template so the API
// compiles before the user runs cf-typegen. Re-run cf-typegen after editing
// `wrangler.jsonc` to regenerate this file from your real bindings.

declare namespace Cloudflare {
  interface Env {
    JWT_SECRET: string;
    API_PUBLIC_HOST: string;
    WEB_PUBLIC_HOST: string;
    WORKER_URL: string;
  }
  interface DevEnv extends Env {}
  interface ProductionEnv extends Env {
    ASSETS: Fetcher;
  }
}

interface CloudflareBindings extends Cloudflare.Env {}
